### ISSUE TITLE
M2-send-to-program in M2-comint-mode

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2-emacs#19]
@eisenbud mentioned that it would be great if F11 didn't duplicate the text entered in an interactive window.

Note that if the cursor is at the _end_ of the partial text, then it's fine:
```m2
i74 : 2+2█ <F11>

o74 = 4
```
However, if the cursor is earlier on the line (not necessarily the beginning), the line is duplicated:
```m2
i74 : █2+2 <F11>
```
result:
```m2
i79 : 2+22+2

o79 = 26
```
Perhaps check if the cursor is on the last line of the buffer, and in that case don't duplicate? Or perhaps duplicate only if there's a newline at the end of the line?

**Comment by d-torrance** [comment]
Using <kbd>Return</kbd> instead of <kbd>F11</kbd>, we don't see this behavior.  Would it make sense to just bind <kbd>F11</kbd> to `M2-send-input` (the same as <kbd>Return</kbd>) in `M2-comint-mode` and make `M2-send-to-program` `M2-mode`-only?
