### ISSUE TITLE
emacs command interpreter prompts now read-only

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/M2-emacs#3]
The emacs command interpreter prompts should not be read-only, since then the user can't delete them.  It even causes an error when the user enters C-d to terminate the process, as this image shows:

<img width="654" alt="Screen Shot 2020-07-14 at 7 56 09 AM" src="https://user-images.githubusercontent.com/700228/87423083-5a14b580-c59f-11ea-9870-c6981e27cfae.png">

It would be good to come up with a work-around for this that people can put in their .emacs files, until 1.17 comes out.

**Comment by mahrud** [comment]
Ah, sure, that variable should have been local. I'll make that change.

I think the error with C-d is coming from somewhere else, which I can try to look into, but it's harmless anyway. The M2 process is still terminated the usual way.

**Comment by DanGrayson** [comment]
> The prompt should always be read-only, otherwise it's confusing for the user when the prompt is erased

No, that choice should be left to the user, as the designers of emacs did, not dictated by us.  Some users want to erase prompts.

**Comment by DanGrayson** [comment]
I'll fix this.

**Comment by mahrud** [comment]
Could you make it local and add a function for toggling the prompt mode,
but leave the default to be read only?

For users who are less familiar with emacs, accidentally deleting the
prompt is always very confusing. Users who are familiar with emacs can
figure out how to disable that themselves.

**Comment by DanGrayson** [comment]
> Could you make it local and add a function for toggling the prompt mode, but leave the default to be read only? For users who are less familiar with emacs, accidentally deleting the prompt is always very confusing. Users who are familiar with emacs can figure out how to disable that themselves.

No, that's a global preference, which the user should be able to set once and for all in the emacs init file.  There's no sense in giving the users whose preferences differ from yours a job to do every time they start Macaulay2 in an emacs session.

**Comment by mahrud** [comment]
This is not just my preference, but a solution to a common problem that
I've observed when introducing beginners to the emacs interface. If you
prefer I can set up a poll to see what people prefer, but do you have a use
case for keeping the prompt modifiable other than simply keeping it this
way because it's always been this way?

Also, M2-init.el is not a standard emacs package file, and I don't think
there's a way to have MELPA install such a file.

**Comment by DanGrayson** [comment]
I'm saying it's not up to us to decide : let the user decide.

**Comment by DanGrayson** [comment]
What you could profitably do is to add a sentence to the emacs documentation, alerting users to the existence of that emacs configuration setting, which they could easily configure if they want the prompts to be read-only in command interpreters such as the emacs shell and Macaulay2.

**Comment by DanGrayson** [comment]
resolved by commit 310601c59196cd70cc105191ce8771676c25f5b4
