### ISSUE TITLE
Add M2-mode to MELPA

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2-emacs#4]
[MELPA](https://melpa.org/) is a package repository for Emacs package recipes. Each [recipe](https://github.com/melpa/melpa#recipe-format) gives the instructions for getting the package from the original source. For instance GAP has the following recipe for gap-mode:
```
(gap-mode
 :fetcher gitlab
 :repo "gvol/gap-mode"
 :files (:defaults "emacs.gaprc"))
```
This recipe points to the package hosted [here](https://bitbucket.org/gvol/gap-mode/src/default/).

The purpose of this issue is to propose moving the emacs directory to a separate M2-mode repository and add a recipe to the [MELPA repository](https://github.com/melpa/melpa). This would allow users to install M2-mode without installing Macaulay2 itself.

## Why?
The main advantage of doing this is that users could install M2-mode, then use `C-u F12` to choose how to run M2, for instance:
  - Remotely via SSH, e.g. `ssh math.umn.edu M2 --no-readline --print-width 125`
  - Remotely via SSH to a containerized version of Habanero!
  - Locally via Docker, e.g. `docker run -it --entrypoint M2 mahrud/macaulay2:v1.15`

Or for developers:
  - Locally from a build directory, without needing permission to install the artifacts on the system

This would mean that any machine running Emacs can run M2 via SSH or docker, and your files would still be saved locally!

The main thing that would need to be done is changing the build system to update the package on a separate M2-mode repository. This could be done via submodules, or we could manually update the M2-mode repository every release.

**Comment by mahrud** [comment]
@DanGrayson now that we're talking about the emacs mode, there are various blocking issues before M2-mode can be added to MELPA. Can you take a look at [these steps](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#making-your-package-ready-for-inclusion)?

**Comment by DanGrayson** [comment]
Okay.  Are any of those problematic for us?

**Comment by mahrud** [comment]
They might require breaking changes.

**Comment by mahrud** [comment]
I wonder if we should rewrite M2-mode based on [Helm](https://emacs-helm.github.io/helm/). It's very helpful.
