### ISSUE TITLE
Jump to files in comments

### ISSUE THREAD

**Issue by d-torrance** [Macaulay2/M2-emacs#6]
> Maybe a better solution would be to fix the Emacs mode so that it will still jump to a file even with -- in front?

Sure, that would be nice. Then `code` can also put `--` before the source code, so the output can be correctly evaluated.

_Originally posted by @mahrud in https://github.com/Macaulay2/M2/issues/1762#issuecomment-752701626_

**Comment by mahrud** [comment]
Here is where the changes would need to occur:
https://github.com/Macaulay2/M2-emacs/blob/54c0c47e352ec2ca2766ac219a41a800767570c7/M2.el#L303-L360
