### ISSUE TITLE
Jump to code slowly diverges from correct line number

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2-emacs#65]
This has been happening for a while now: if I'm working in the same file for a long time and clicking on error lines to jump to the source code in that file frequently, slowly the place where emacs jumps to starts to diverge from the correct line number, eventually getting dozens of lines away before I just give up and close/reopen the file to fix it.

@mikestillman has apparently noticed this to, so it's not just my emacs setup.

**Comment by mahrud** [comment]
@d-torrance have you noticed this as well?

**Comment by mahrud** [comment]
Ah, yes, I can reproduce these steps. In fact, reverting https://github.com/Macaulay2/M2-emacs/commit/5b68215b9ab4a9460b0ac81d9a73cf890cfca9cb seems to resolve the problem.

**Comment by d-torrance** [comment]
I'd rather keep using compilation minor mode -- it has some nice features and in general I think it's more idiomatic to Emacs than rolling our own function like we used to.  I imagine there's a way to turn off the automatic updating of line numbers -- I'll play around with it.
