### ISSUE TITLE
M2-menu

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2-emacs#66]
When I run `M-x M2-menu` in Emacs I get just a message:
> M2-menu must be bound to an event with parameters

What is `M2-menu` for, and how does one use it?

**Comment by d-torrance** [comment]
It's responsible for the "Macaulay2" menu that appears in the Emacs toolbar.  I don't think it's supposed to be run directly (it's defined using `easy-menu-define` rather than `defun`).  We get the same message when we run similar functions for other major modes directly (e.g., `M-x python-menu`).

**Comment by mahrud** [comment]
Ah I see, thank you!
