### ISSUE TITLE
Bug in highlighting stdio position

### ISSUE THREAD

**Issue by mahrud** [Macaulay2/M2-emacs#71]
I just ran into this:
![image](https://github.com/user-attachments/assets/48b7ffd6-9afb-4138-886d-582959c754d9)

**Comment by mahrud** [comment]
![image](https://github.com/user-attachments/assets/09baf43b-948d-4339-a5a1-cac657372f80)

**Comment by d-torrance** [comment]
While we're at it, are there any other characters that might immediately precede a file position and we should account for in the regex?  Maybe an opening parenthesis?

```m2
i1 : 1:locate(ideal, List)

o1 = 1 : (/usr/share/Macaulay2/Core/matrix1.m2:571:41-571:104)
```

**Comment by mahrud** [comment]
Why not try excluding everything other than characters that appear unescaped in strings? So letters, numbers, and `/ . ~`, right? (and perhaps filenames with special characters should be formatted? idk, I'm happy to not detect really weird filenames ...)

**Comment by d-torrance** [comment]
Yeah, that makes sense.  There's a [POSIX "portable filename character set"](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_282) that should catch the vast majority of filenames.

**Comment by mahrud** [comment]
How come this repo auto-closes issues but not M2?

**Comment by d-torrance** [comment]
They get auto-closed when they hit the default branch.  So in the M2 repo, they'll eventually auto-close whenever we merge `development` into `master`.

**Comment by mahrud** [comment]
Ahh right right
